### ISSUE TITLE
 User Model

### ISSUE THREAD

**Issue by Rishi-Raj-Kalita** [knight-18/Medical-Records#3]
1. The user model will contain the userSchema containing the fields name,password,email and phone number
2. Contains a generateAuth function which returns a jwt when called
3. Contains a function for hashing the password of the user

---Future Scopes-
1.Function for finding credential of the user
2.Function for deleting the uploads of the user when the user deletes his profile

**Comment by knight-18** [comment]
Create branch with the name issue-<issueNo>.
Push your code in that branch and raise PR.

**Comment by Rishi-Raj-Kalita** [comment]
okay bhaiya sure

**Comment by knight-18** [comment]
Basic user model created.
Closing this issue.
