### ISSUE TITLE
Adding authentication

### ISSUE THREAD

**Issue by Debojyoti1915001** [knight-18/Medical-Records#4]
Description : 
- Added middleware for authorization
-  Add app.js to handle all routes
- Add nodemailer.js to send email to the user for verification.

**Comment by knight-18** [comment]
While creating it keep it like:
- Add middleware for authorzation.
- add index.js 

Center of everything has no reference.
You can write 
- Add index.js to handle all routes

Once you are done with the issue then you can write added and close it then.
