### ISSUE TITLE
Login/Signup Issues to be Fixed 

### ISSUE THREAD

**Issue by ujjawal-1999** [knight-18/Medical-Records#78]
![Screenshot from 2020-11-19 00-56-40](https://user-images.githubusercontent.com/43065268/99581428-cfd5d580-2a06-11eb-9fc1-25d16fef9b2c.png)

- [x] **1. Make the flash message center aligned and also add an icon to close the message. Also, the flash message should disappear itself after 5-6 seconds**

![Screenshot from 2020-11-19 00-58-12](https://user-images.githubusercontent.com/43065268/99581456-d6fce380-2a06-11eb-93b2-8bfe2a3a917a.png)

- [x] **2. Resolve SMTP Error**

![Screenshot from 2020-11-19 01-10-30](https://user-images.githubusercontent.com/43065268/99581516-ec720d80-2a06-11eb-9896-9e5035abf7ac.png)

- [x] **3. Incase of error while logging in, I am redirected to the signup section after page reload, should be redirected to the Login section**

![Screenshot from 2020-11-19 01-12-45](https://user-images.githubusercontent.com/43065268/99581549-f5fb7580-2a06-11eb-8475-8a59ecfd282c.png)

- [ ] **4. Incase of the same letter being repeated multiple times, the progress bar is not visible**

![Screenshot from 2020-11-19 01-18-50](https://user-images.githubusercontent.com/43065268/99581557-f98efc80-2a06-11eb-8d1c-9fd3a3bf9f6f.png)

- [x] **5. Invalid Credentials shows error on console**

![Screenshot from 2020-11-19 01-01-12](https://user-images.githubusercontent.com/43065268/99581470-da906a80-2a06-11eb-8a29-31badca9be17.png)

- [ ] **6. Overflow when the password details div is shown. Also, this div should appear below the password input**

![Screenshot from 2020-11-19 01-08-24](https://user-images.githubusercontent.com/43065268/99581476-dc5a2e00-2a06-11eb-8344-8aa8d133a076.png)

- [x] **7. Login button should be a cursor pointer**

![Screenshot from 2020-11-19 01-01-25](https://user-images.githubusercontent.com/43065268/99581485-e0864b80-2a06-11eb-90a5-be19acb783e5.png)

- [x] **8. On clicking on the Password and then clicking on the Confirm password the password details are shown and this is repeated if I again click on Password and then Confirm Password. Morever, there is no scroll option to see the Login Button now**

**Comment by nishisekhani** [comment]
**Assigning No. 4, 6, 7, 8 of this issue to myself**

**Comment by Debojyoti1915001** [comment]
Assigning number 2 of this issue to myself.

**Comment by guilefoylegaurav** [comment]
Assigning issue 5 to myself

**Comment by aditya2712** [comment]
**Assigning numer 1 of this issue to myself**

**Comment by aditya2712** [comment]
Bhaiya, this issue is resolved, please close this issue.
