### ISSUE TITLE
Add icon in register page to show password criteria

### ISSUE THREAD

**Issue by knight-18** [knight-18/Medical-Records#80]
Add information kind of icon to the right side of the input field.
On hovering over it show the validation points for a strong password.

![passwordBug](https://user-images.githubusercontent.com/56457032/99764455-1b7da180-2b23-11eb-985b-bdb139dacbf7.png)

**Comment by Sujata-Baroi** [comment]
Bhaiya, this issue is resolved .Please close this issue.
