### ISSUE TITLE
Home Page Bugs

### ISSUE THREAD

**Issue by ujjawal-1999** [knight-18/Medical-Records#91]
- [x] Navbar and Footer should be partials.

- [x]  The position of the flash message needs to be fixed.
![Screenshot from 2020-11-24 00-01-01](https://user-images.githubusercontent.com/43065268/100001211-cd99bf80-2de8-11eb-8bd3-551d89cab607.png)

- [x] The Contact form Js needs to be checked properly

- [x] The Outline form submit button needs to be removed
![Screenshot from 2020-11-24 00-01-09](https://user-images.githubusercontent.com/43065268/100001282-e73b0700-2de8-11eb-8edb-53565727af7e.png)

- [x] Test the contact form for any bugs.

**Comment by ujjawal-1999** [comment]
Deadline - 25th 10 am.

**Comment by aditya2712** [comment]
navar and footer (partials) assigning to myself

**Comment by abinashstack** [comment]
The Contact form js assigning to myself
